# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_product_codes.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brequest_product_codes.proto\x12\x03rti\"\xa8\x01\n\x13RequestProductCodes\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x01(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x17\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\tH\x00\x88\x01\x01\x12%\n\x16give_toi_products_only\x18\x9b\xaf\t \x01(\x08H\x01\x88\x01\x01\x42\x0b\n\t_exchangeB\x19\n\x17_give_toi_products_onlyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_product_codes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTPRODUCTCODES']._serialized_start=37
  _globals['_REQUESTPRODUCTCODES']._serialized_end=205
# @@protoc_insertion_point(module_scope)
