# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_auxilliary_reference_data.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'request_auxilliary_reference_data.proto\x12\x03rti\"\x93\x01\n\x1eRequestAuxilliaryReferenceData\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x01(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x15\n\x06symbol\x18\x94\xdc\x06 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_symbolB\x0b\n\t_exchangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_auxilliary_reference_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTAUXILLIARYREFERENCEDATA']._serialized_start=49
  _globals['_REQUESTAUXILLIARYREFERENCEDATA']._serialized_end=196
# @@protoc_insertion_point(module_scope)
