# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_product_codes.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cresponse_product_codes.proto\x12\x03rti\"\xca\x03\n\x14ResponseProductCodes\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x01(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x1c\n\x12rq_handler_rp_code\x18\x9c\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x17\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\x0bsymbol_name\x18\xa3\x8d\x06 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0cproduct_code\x18\x8d\x93\x06 \x01(\tH\x02\x88\x01\x01\x12(\n\x19timezone_time_of_interest\x18\xba\xb8\t \x01(\tH\x03\x88\x01\x01\x12)\n\x1a\x62\x65gin_time_of_interest_msm\x18\xb8\xb8\t \x01(\x05H\x04\x88\x01\x01\x12\'\n\x18\x65nd_time_of_interest_msm\x18\xb9\xb8\t \x01(\x05H\x05\x88\x01\x01\x42\x0b\n\t_exchangeB\x0e\n\x0c_symbol_nameB\x0f\n\r_product_codeB\x1c\n\x1a_timezone_time_of_interestB\x1d\n\x1b_begin_time_of_interest_msmB\x1b\n\x19_end_time_of_interest_msmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_product_codes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSEPRODUCTCODES']._serialized_start=38
  _globals['_RESPONSEPRODUCTCODES']._serialized_end=496
# @@protoc_insertion_point(module_scope)
