# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_login_info.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19response_login_info.proto\x12\x03rti\"\xc9\x05\n\x11ResponseLoginInfo\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x01(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x0e\n\x04user\x18\xbb\xff\x07 \x01(\t\x12\x14\n\nfirst_name\x18\xe8\xb4\t \x01(\t\x12\x13\n\tlast_name\x18\xe9\xb4\t \x01(\t\x12\x17\n\remail_address\x18\xde\x94\t \x01(\t\x12\x34\n\tuser_type\x18\xb4\xb3\t \x01(\x0e\x32\x1f.rti.ResponseLoginInfo.UserType\x12\x1b\n\x11order_copy_status\x18\xfe\xd3\t \x01(\t\x12\x16\n\x0c\x63ountry_code\x18\xd8\xb8\t \x01(\t\x12\x14\n\nstate_code\x18\xd9\xb8\t \x01(\t\x12\x1a\n\x10\x61\x64\x64ress_street_1\x18\xff\xe8\x08 \x01(\t\x12\x1a\n\x10\x61\x64\x64ress_street_2\x18\x80\xe9\x08 \x01(\t\x12\x16\n\x0c\x61\x64\x64ress_city\x18\x81\xe9\x08 \x01(\t\x12\x17\n\raddress_state\x18\x82\xe9\x08 \x01(\t\x12\x19\n\x0f\x61\x64\x64ress_country\x18\x83\xe9\x08 \x01(\t\x12\x15\n\x0b\x61\x64\x64ress_zip\x18\x87\xe9\x08 \x01(\t\x12\x19\n\x0fphone_residence\x18\x84\xe9\x08 \x01(\t\x12\x14\n\nphone_work\x18\x85\xe9\x08 \x01(\t\x12\x16\n\x0cphone_mobile\x18\x86\xe9\x08 \x01(\t\x12\x1e\n\x14tp_max_session_count\x18\xe0\xc5\x08 \x01(\x05\x12\x1e\n\x14op_max_session_count\x18\xec\xc5\x08 \x01(\x05\"Z\n\x08UserType\x12\x13\n\x0fUSER_TYPE_ADMIN\x10\x00\x12\x11\n\rUSER_TYPE_FCM\x10\x01\x12\x10\n\x0cUSER_TYPE_IB\x10\x02\x12\x14\n\x10USER_TYPE_TRADER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_login_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSELOGININFO']._serialized_start=35
  _globals['_RESPONSELOGININFO']._serialized_end=748
  _globals['_RESPONSELOGININFO_USERTYPE']._serialized_start=658
  _globals['_RESPONSELOGININFO_USERTYPE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
